<?php
$items = $block->getOrderedItems();
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>
<form action="" method="post" id="list-reoderproduct" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
    <div class="list-reoderproduct" style="overflow-x:auto;">
        <table id="reorder_product" class="display table table-striped" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th style="width:10%;"><input type="checkbox" name="item[]" value="all" id="reorder-select-all"></th>
                    <th style="width:20%;"><?php /* @escapeNotVerified */ echo __('Image')?></th>
                    <th style="width:30%;"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th style="width:15%;"><?php /* @escapeNotVerified */ echo __('Ordered Price') ?></th>
                    <th style="width:15%;"><?php /* @escapeNotVerified */ echo __('Ordered Qty') ?></th>
                    <th style="width:10%;"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                </tr>
            </thead>
            <tbody>
        <?php if ($items->getSize()) {
                foreach ($items as $item):
                    $productId = $item->getProductId();
                    $_product = $block->getProductById($productId);
                    $parentId = $block->getParentId($productId);
                    if ($parentId) {
                        $_parent = $block->getProductById($parentId);
                        $productUrl = $_parent->getProductUrl();
                    } else {
                        $productUrl = $_product->getProductUrl();
                    }
                    ?>
                    <tr>
                        <td>
                            <input type="checkbox" name="item[]" id="item_<?php /* @escapeNotVerified */ echo $productId; ?>" value="<?php /* @escapeNotVerified */ echo $productId; ?>" class="reorder-select-item">
                            <input type="hidden" id="parent_<?php /* @escapeNotVerified */ echo $productId ;?>" name="parent_<?php /* @escapeNotVerified */ echo $productId ;?>" value="<?php /* @escapeNotVerified */ echo $parentId; ?>">
                        </td>
                        <td>
                            <div class="image-reoderproduct">
                                <img class="thumbnail" src="<?php /* @escapeNotVerified */ echo $imageHelper->init($_product, 'category_page_list', array('height' => 100 , 'width'=> 100))->getUrl();?>" alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php /* @escapeNotVerified */ echo $_product->getName(); ?>" />
                            </div>
                        </td>
                        <td>
                            <p class="product-name"><span><a href="<?php echo $productUrl;?>" ><?php /* @escapeNotVerified */ echo $_product->getName(); ?></a></span></p>
                            <p><span><?php /* @escapeNotVerified */ echo $_product->getSku(); ?></span></p>
                        </td>
                        <td>
                            <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_product->getPrice(),true, false);
                            ?>
                        </td>
                        <td class="qtyordered-reorder">
                            <?php /* @escapeNotVerified */ echo (int)$item->getTotalQty();?>
                        </td>
                        <td class="qty-reorder">
                            <input type="text" id="qty_<?php /* @escapeNotVerified */ echo $productId ;?>" name="qty_<?php /* @escapeNotVerified */ echo $productId ;?>" value="1" class="qty-reoderproduct">
                        </td>
                    </tr>
                <?php
                endforeach;
            } else { ?>
                <tr>
                    <td colspan="6">No Record Found</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</form>